version: '3.8'
services:
  postgres:
    image: postgres
    container_name: go-rest-api-db
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev123
      POSTGRES_DB: exploration
